### ISSUE TITLE
I915 arbiter required

### ISSUE THREAD

**Issue by noenthu** [jessequinn/manjaro_custom_kernel_linux419-4.20.12-1_ACS_override#1]
Looking at the package in aur it leverages an i915 arbiter patch. Is that needed?

**Comment by jessequinn** [comment]
I use OVMF. Never had a need for i915 arbiter patch. However, I would suggest using my 4.19 or 5.0 kernel as the 4.20 is EOL. so a security issue in the future.

**Comment by noenthu** [comment]
Thanks for the info @jessequinn. 
Is it possible to have both mainline 4.19 and the patched version coexist? I ran into an issue when I tried to build 419 with the patch since pacman found existing /vmlinuz_linx419

**Comment by jessequinn** [comment]
as it stands, i overwrite the default version as you have seen. To have the custom kernel stand next to your default 4.19 you need to rename portions of the PKGBUILD. 

this [https://forum.manjaro.org/t/how-to-compile-the-mainline-kernel-the-manjaro-way/51700/55](url) may help you.

**Comment by jessequinn** [comment]
i will close this issue as it appears resovled.
